config/routes.rb
Rails.application.routes.draw do
  devise_for :registrations, :controllers => {registrations: "registrations"}
  resources :wages, only: [ :create, :new ]
  post 'preview', to: 'wages#preview'
  get 'preview', to: 'pages#test'
  get 'fields', to: 'users#fields'
  get 'companies', to: 'users#companies'
  resources :users, only: [ :index, :create ]
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :wages, dependent: :destroy
  validates :name, presence: true

  def field_average(field)
    wages = self.wages.select { |wage| wage.field == field }
    wages.map!(&:wage)
    sum = wages.inject(0){|sum,x| sum + x }
    return 0 if wages.size == 0
    return sum / wages.size
  end

  include AlgoliaSearch

  algoliasearch do
    attribute :name
  end
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :wages, dependent: :destroy
  validates :name, presence: true

  def companies_hash
    companies_hash = {}
    Company.all.each do |company|
      companies_hash[company.name] = company.field_average(self)
    end
    companies_hash.sort_by { |_key, value| value }.reverse
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :user
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :registration
  has_one :wage
end

app/models/wage.rb
class Wage < ApplicationRecord
  belongs_to :user
  belongs_to :field
  belongs_to :company
  validates :wage, presence: true, inclusion: 100..10000000
  validates :years_worked, presence: true, inclusion: 1..80
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_registration!
  attr_reader :current_user
  helper_method :current_user, :user_signed_in?

  def current_user
    @current_user ||= current_registration.try(:user)
  end

  def user_signed_in?
    registration_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_registration!, only: :home

  def home
    redirect_to new_wage_path if user_signed_in?
    @field = Field.all
  end
  def test
    render 'wages/preview'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super do
      User.create(registration_id: resource.id)
    end
  end

  protected

  def after_sign_up_path_for(resource)
    new_wage_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @current_page = 'user'
    @companies = Company.all
    @user = current_user.registration.email
    @wage = Wage.all
    calc = CalculatorService.new({ wage: current_user.wage.field.avg_wage,
                                   years: 17,
                                   years_new: current_user.wage.years_worked })
    @should_be_making = calc.new_wage.to_i
    @yr_1 = wage_progression(1)
    @yr_2 = wage_progression(2)
    @yr_3 = wage_progression(3)
    @yr_4 = wage_progression(4)
    @yr_5 = wage_progression(5)
    @yr_10 = wage_progression(10)
    @user_field = current_user.wage.field

    if @should_be_making < current_user.wage.wage
      @how_you_are_doing = "doing well"
    else
      @how_you_are_doing = "ask for more"
    end
  end

  def wage_progression(years)
    CalculatorService.new({wage: current_user.wage.wage,
                           years: current_user.wage.years_worked,
                           years_new: current_user.wage.years_worked + years })
                           .new_wage.to_i + inflation(years)
  end

  def inflation (years)
    ((current_user.wage.wage * 1.024**years) - current_user.wage.wage).to_i
  end

  def fields
    @current_page = 'fields'
    @fields = Field.all

    @field_name = []
    @field_avg_wage = []
    @fields.each do |field|
      @field_name << field.name
      @field_avg_wage << field.avg_wage
    end
  end

  def companies
    @current_page = 'companies'
    @company_avg = CompanyAverageService.new(current_user.wage.field, current_user.wage.company).company_avg
    @company_data = current_user.wage.field.companies_hash
  end
end

app/controllers/wages_controller.rb
require 'json'

class WagesController < ApplicationController
  skip_before_action :authenticate_registration!, only: :preview

  def index
  end

  def new
    @wage = Wage.new
    @fields = Field.all
    redirect_to users_path if current_user.wage
  end

  def create
    @wage = Wage.new
    @wage.field = Field.find(wages_params[:field_id])
    @wage.company = Company.find_by_name(wages_params[:company])
    @wage.years_worked = wages_params[:years_worked].to_i
    @wage.wage = wages_params[:wage].to_i
    @wage.user = current_user
    if @wage.save
      redirect_to users_path
    else
      render :new
    end
  end

  def preview
    field_avg_wage = Field.where(name: params["field"]["name"])[0].avg_wage
    calc = CalculatorService.new({ wage: field_avg_wage,
                                   years: 17,
                                   years_new: params["years"] })
    @result = calc.new_wage.to_i
    @field = params["field"]["name"]
    @years = params["years"]
  end

  private

  def wages_params
    params.require(:wage).permit(:wage, :field_id, :company, :years_worked)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
  def fields_by_average_wage_chart
    # @fields = Field.all

    # @fields.group(:name).count, height: '100px', library: {
    #   title: {text: "Average Wage by Field", x: -20},
    #   yAxis: {
    #     allowDecimals: false,
    #     title: {
    #       text: 'Fields'
    #     }
    #   },
    #   xAxis: {
    #     title: {
    #       text: 'Wage'
    #     }
    #   }
    # }
  end
end

app/views/field/show.html.erb
<h1>Field#show</h1>
<p>Find me in app/views/field/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

    <meta charset="UTF-8">

    <!-- Favicon -->
    <%= favicon_link_tag 'favicon.ico'  %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Open Graph Data -->
    <meta property="og:title" content="Get paid more" />
    <meta property="og:url" content="http://wagefinder.herokuapp.com" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Find out exactly how much you're worth with your personalized Market Salary. Negotiate your offer or get a raise with confidence." />
    <meta property="og:image" content="https://static.seattletimes.com/wp-content/uploads/2017/07/web-4-tips-higher-salary-web-1200x630.jpg" />

    <title>WageFinder, get paid more. Find what you're really worth.</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="front_wrapper">
  <div id="logo">
    <div class="logo_green">
      <h3> Wage </h3>
    </div>
    <div class="logo_black">
      <h3 class="finder"> Finder</h3>
    </div>
  </div>


  <h1 class="discover_text"> Discover</br> your field's</br> average wage</h1>

  <%= render 'shared/form_main' %>

<!--   <div>
    <a href="" class="btn"></a>
  </div> -->

</div>

app/views/shared/_button_main.html.erb
  <div>
      <a href=“#” class="btn">Submit</a>
  </div>

app/views/shared/_button_regular.html.erb
  <div>
      <a href=“#” class="btn-regular">Submit</a>
  </div>

app/views/shared/_chart.html.erb
<canvas id="myChart"></canvas>

app/views/shared/_charts.html.erb
<div class="chart-container">
  <canvas id="myChart"></canvas>
</div>

<script type="text/javascript">

  var ctx = document.getElementById('myChart').getContext('2d');
  var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'horizontalBar',

    // The data for our dataset
    data: {
        labels: <%= raw @field_name.to_json %>,
        datasets: [{
            label: null,
            backgroundColor: ['#ffe0ae', '#ffb100','#ffe0ae', '#ffb100','#ffe0ae', '#ffb100','#ffe0ae', '#ffb100', '#ffe0ae'],
            // borderColor: 'rgb(255, 99, 132)',
            data: <%= raw @field_avg_wage.to_json %>,
        }]
    },
    // Configuration options go here
    options: {
      responsive: true,
      maintainAspectRatio: false,
      layout: {
        padding: {
          top: 20
        }
      },
      legend: {
        display: false
      },
    scales: {
    yAxes: [{
        barThickness : 23,
        ticks: {
          fontSize: 15,
          fontStyle: 'bold'
        },
        gridLines: {
          display:false
        }
      }],
    xAxes: [{
        ticks: {
          fontSize: 15,
          fontStyle: 'bold'
        },
    }],
    }
  }
});
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form_main.html.erb
<%= form_tag preview_path, method: :post, class: "form_tag" do %>
  <%= collection_select(:field, :name, Field.all, :name, :name, prompt: true) %>
  <input type="text" class="form_secondary" name="years" placeholder="Years of experience">
  <%= submit_tag "Submit", data: { disable_with: "Please wait.." }, class: "btn" %>
<% end %>

app/views/shared/_form_regular.html.erb
    <%= simple_form_for @wage do |f| %>
      <%= f.error_notification %>
      <%= f.input :wage, label: false, placeholder: "Salary" %>
      <%= f.input :company, label: false, placeholder: "Company" %>
      <%= f.input :years_worked, label: false, placeholder: "Years worked" %>
      <%= f.input :field, label: false, placeholder: "Field" %>
      <%= f.button :submit %>
    <% end %>

app/views/shared/_logo.html.erb
  <div id="logo">
    <div class="logo_green">
      <h4><%= link_to 'Wage', users_path %></h4>
    </div>
    <div class="logo_black">
      <h4 class="finder"> Finder</h4>
    </div>
  </div>

app/views/shared/_pagination.html.erb
<div class="pagination">
 <% num = @company_data.length.to_f/6 %>
 <% num.ceil.times do |i| %>
   <button class="btn-pagination" onClick="clickHandler(event)"><%= i + 1 %></button>
 <% end %>
</div>

app/views/shared/_table.html.erb
<table class="info_table" border="1" cellpadding="8" cellspacing="0" bordercolor="#dddddd">
  <tbody>
    <% count = 0 %>
    <% bundle_count = 1 %>
    <% @company_data.each do |company, avg| %>
      <tr class="<%= bundle_count  %> pagination-hidden company-wage-info">
        <td><%= company %></td>
        <td><strong><%= number_with_delimiter(avg) %>€<strong></td>
      </tr>
      <% count += 1 %>
      <% if count == 6 %>
        <% bundle_count += 1 %>
        <% count = 0 %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/shared/_tabs.html.erb
<div class="tabs">
  <% if @current_page == 'companies' %>
    <%= link_to 'Compare fields', fields_path, class: 'tab' %>
    <%= link_to 'Browse companies', companies_path, class: 'tab active' %>
  <% elsif @current_page == 'fields'%>
    <%= link_to 'Compare fields', fields_path, class: 'tab active' %>
    <%= link_to 'Browse companies', companies_path, class: 'tab' %>
  <% else %>
    <%= link_to 'Compare fields', fields_path, class: 'tab' %>
    <%= link_to 'Browse companies', companies_path, class: 'tab' %>
  <% end %>
</div>

app/views/users/companies.html.erb
<div class="index-wrapper">
  <%= render 'shared/logo' %>
  <%= render 'shared/tabs' %>
  <div class="index-less-button">
<h2 class="company-average-header"> <%= number_with_delimiter(@company_avg ) %>€ </h2>
<h6> Is the average wage<br>
     for <%= current_user.wage.field.name %>s <br>
     at <%= current_user.wage.company.name %>  </h6><br>

<%= render 'shared/table' %>
<%= render 'shared/pagination' %>

</div>

<%= button_to 'Back to report', users_path, method: :get %>
</div>

app/views/users/fields.html.erb
<div class="index-wrapper">
  <%= render 'shared/logo' %>
  <%= render 'shared/tabs' %>

  <%= render 'shared/charts' %>
  <%= button_to 'Back to report', users_path, method: :get %>
</div>

app/views/users/index.html.erb
<div class="index-wrapper">
  <%= render 'shared/logo' %>
  <%= render 'shared/tabs' %>

  <% if @how_you_are_doing == 'doing well' %>
    <h2 class="doing_well"><%= @how_you_are_doing %></h2>
    <div id="badges-wrapper">
      <div id="your-wage">
        <i class="fa fa-user" aria-hidden="true"></i>
        <h6>Your salary: <br><strong><%= number_with_delimiter(current_user.wage.wage) %>€</strong></h6>
      </div>

  <% else %>
    <h2 class="ask_more"><%= @how_you_are_doing %></h2>
    <div id="badges-wrapper">
      <div id="your-wage-bad">
        <i class="fa fa-user" aria-hidden="true"></i>
        <h6>Your salary: <br><strong><%= number_with_delimiter(current_user.wage.wage) %>€</strong></h6>
      </div>
  <% end %>


    <div id="field-wage">
      <i class="fa fa-users" aria-hidden="true"></i>
      <h6>Field average: <br><strong><%= number_with_delimiter(@should_be_making) %>€</strong></h6>
    </div>
  </div>
    <button id="browse" class="btn">
    Projected Wage
  </button>
</div>





<div id="wage-progression-wrapper">
  <div class="wage-row-wrapper-header">
    <h6 class="years-header"> Years </h6>
    <h6 class="projected-years-header"> Projected salary </h6>
  </div>
  <div class="wage-row-wrapper">
    <div class="year-circle">1</div>
    <div class="projected-wage"><%= number_with_delimiter(@yr_1)%>€</div>
  </div>
   <div class="wage-row-wrapper">
    <div class="year-circle">2</div>
    <div class="projected-wage"><%= number_with_delimiter(@yr_2)%>€</div>
  </div>
   <div class="wage-row-wrapper">
    <div class="year-circle">3</div>
    <div class="projected-wage"><%= number_with_delimiter(@yr_3)%>€</div>
  </div>
   <div class="wage-row-wrapper">
    <div class="year-circle">4</div>
    <div class="projected-wage"><%= number_with_delimiter(@yr_4)%>€</div>
  </div>
   <div class="wage-row-wrapper">
    <div class="year-circle">5</div>
    <div class="projected-wage"><%= number_with_delimiter(@yr_5)%>€</div>
  </div>
  <div class="wage-row-wrapper">
    <div class="year-circle">10</div>
    <div class="projected-wage"><%= number_with_delimiter(@yr_10)%>€</div>
  </div>
</div>

  <%= button_to 'Logout', destroy_registration_session_path, method: :delete %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/wages/new.html.erb
<div class="form-wrapper">
  <div class="navbar">
    <%= render 'shared/logo' %>
  </div>
    <h3> Help us refine</br> your results </h3>
  <div class="form-minus-button">
  <%= simple_form_for @wage do |f| %>
    <%= f.error_notification %>
    <%= f.input :wage, label: false, placeholder: "Yearly salary (€)" %>
    <%= f.input :company, label: false, placeholder: "Company", input_html: { id: "aa-search-input", autocomplete: "off" } %>
    <%= f.input :years_worked, label: false, placeholder: "Years worked" %>
    <%= f.input :field_id, collection: @fields, label: false, selected: "Pick a field" %>
  </div>
    <%= f.button :submit, 'See your report' %>
  <% end %>
</div>

app/views/wages/preview.html.erb
<div class="preview-wrapper">
  <%= render 'shared/logo' %>
  <div class="preview-less-button">
  <h1 class="amount-money"><%= number_with_delimiter(@result ) %>€</h1>
  <h1 class="job-title-years"> for <%= @years %> years as</br> a <%= @field %></h1>
   <%= image_tag("bills_phone.png")%>
  </div>
  <%= image_tag("teaser.jpg")%>
  <%= button_to "Get free report", new_registration_registration_path, method: :get %>
</div>